name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build docs
        run: npm run docs:build

      - name: copy image
        run: cp -r docs/source/image/ docs/.vuepress/dist/source/

      - name: Deploy to GitHub Pages Assets
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: huanhuan0812/huanhuan0812.github.io
          publish_dir: ./docs/.vuepress/dist/source
          destination_dir: source
          keep_files: false
          force_orphan: false
          publish_branch: main
          user_name: 'github-actions[bot]'
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
          deploy_key: ${{secrets.ACTIONS_DEPLOY_KEY}}

      - name: Kill existing SSH agent
        run: |
          pkill -f "ssh-agent -a /tmp/ssh-auth.sock" || true
          rm -f /tmp/ssh-auth.sock

      - name: Wait 5s to avoid SSH conflict
        run: sleep 10

      - name: Deploy to GitHub Pages Souece
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: huanhuan0812/huanhuan0812.github.io
          publish_dir: ./docs/.vuepress/dist/assets
          destination_dir: ""
          keep_files: true
          force_orphan: false
          publish_branch: main
          user_name: 'github-actions[bot]'
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
          deploy_key: ${{secrets.ACTIONS_DEPLOY_KEY}}
